receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    limit_mib: 256
    check_interval: 1s
  batch:
    timeout: 1s
    send_batch_size: 1024
  resource:
    attributes:
      - key: service.instance.id
        from_attribute: service.name
        action: insert
      - key: telemetry.auto.version
        value: "demo"
        action: insert

exporters:
  # Export to Jaeger via OTLP
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  
  # Debug exporter (replaces deprecated logging exporter)
  debug:
    verbosity: detailed

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlp, debug]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug]
      
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug] 